[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/capstone-key.pem

[jenkins_master]
jenkins-master ansible_host=10.0.150.193

[jenkins_agents]
jenkins-worker-1 ansible_host=10.0.156.246

[sonarqube]
sonarqube-server ansible_host=10.0.157.201

[build_tools]
maven-trivy-server ansible_host=10.0.150.203

[app_servers]
app-server-1 ansible_host=10.0.135.64
app-server-2 ansible_host=10.0.42.112

[bastion]
bastion-host ansible_host=10.0.146.127

[redis]
redis-server ansible_host=10.0.158.239
